### ISSUE TITLE
Research the best approach to setup a pub/sub system inside fuel-core

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/data-systems#1]
The goal is to research and determine the best approach for implementing a pub/sub system that will be triggered for each new block within `fuel-core`. As we have decided to use NATS as the messaging mechanism, it would be helpful to outline how to handle it in a way that will not be tightly integrated within the core.

**Comment by Jurshsmith** [comment]
Discussion: https://github.com/FuelLabs/data-systems/discussions/9

**Comment by pedronauck** [comment]
Research done.
