### ISSUE TITLE
Patch Versioning for Dependencies

### ISSUE THREAD

**Issue by Jurshsmith** [FuelLabs/data-systems#10]
Is there a reason we should lock `patch` versions? My main concern is that if there is a security `patch`, this would create an extra step to catch up.

_Originally posted by @Jurshsmith in https://github.com/FuelLabs/data-systems/pull/4#discussion_r1624171152_

**Comment by pedronauck** [comment]
No, there's no specific reason, we can go directly with minor if you think is better. The only concern is that we will been always updating `Cargo.lock`, so it's essential to have audit actions running properly to avoid automatically updates having bad minor versions.
