### ISSUE TITLE
Set up NATS message deduplication

### ISSUE THREAD

**Issue by lostman** [FuelLabs/data-systems#28]
### Motivation

We can use NATS's built-in deduplication feature to ensure each message is delivered only once.

For that, we need to set the message ID.

Since each message we publish is uniquely identified by it's full topic, I think we can simply set the message_id to be the same as topic (.e.g. `blocks.12345`).

In Rust, the call to publish (with a custom message ID) will look like:

```
    /// let ack = jetstream
    ///     .send_publish(
    ///         "events",
    ///         Publish::build().payload("data".into()).message_id("uuid"),
    ///     )
    ///     .await?;
```

See

https://docs.nats.io/using-nats/developer/develop_jetstream/model_deep_dive#message-deduplication

for more details.

**Comment by pedronauck** [comment]
Closed on #107
